name: wt_logging
description: Component to manage logging, user logs and SnackBar messages.
version: 1.0.0+1
homepage: https://github.com/tmcmaster/wt_logging
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: 1.12.30
  logger: ^1.4.0
  flutter_riverpod: ^2.3.6
  lint: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
#  mockito:

flutter: