name: wt_logging
description: Component to manage logging, user logs and SnackBar messages.
version: 0.0.1
homepage: https://github.com/tmcmaster/wt_logging
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger:
  flutter_riverpod:
  lint:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
#  mockito:

flutter: