name: wt_logging
description: Component to manage logging, user logs and SnackBar messages.
version: 1.0.3+3
homepage: https://github.com/tmcmaster/wt_logging
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar:
  flutter_riverpod:
  lint:
  logger:
  package_info_plus: ^8.3.0
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6

flutter: